# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2016-01-05 10:07
from __future__ import unicode_literals

import demo.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AffiliatedSchool',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('school_name', models.CharField(max_length=100, unique=True)),
                ('science_club_members_count', models.PositiveIntegerField()),
                ('teacher_name', models.CharField(max_length=100)),
                ('contact_no', models.CharField(max_length=20)),
                ('years_affiliated', models.PositiveIntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Member',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('id_number', models.CharField(max_length=10, validators=[demo.validators.validate_id_number])),
                ('last_name', models.CharField(max_length=50)),
                ('given_name', models.CharField(max_length=50)),
                ('middle_name', models.CharField(max_length=50)),
            ],
        ),
    ]
